project 'YXEmptyPlaceHolder.xcodeproj'

# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'
platform:ios ,'7.0'


target 'YXEmptyPlaceHolder' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for YXEmptyPlaceHolder
pod 'AFNetworking'
pod 'MJRefresh'
pod 'MJExtension'
pod 'MBProgressHUD'
pod 'Masonry'

  target 'YXEmptyPlaceHolderTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'YXEmptyPlaceHolderUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
